apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
  namespace: employee-portal
spec:
  replicas: 5
  selector:
   matchLabels:
    app: frontend
  template:
   metadata:
    labels:
     app: frontend
   spec:
    containers:
     - name: nginx
       image: umangkhandelwal/prtapril2026:v1
